# Generated by Django 4.0.4 on 2022-05-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('severity', models.CharField(max_length=10)),
                ('cvss', models.FloatField(blank=True, default=None, null=True)),
                ('publication_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
